name: Docker Release

on:
  push:
    tags: [ "v*" ]
  pull_request:
    tags: [ "v*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    -
      name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
    -
      name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Release Note

          We regularly update the Docker images to reflect version changes of the included MCCS toolchain and third-party software. For more information about the MCCS toolchain, please refer to its main repository [mccs-toolchain](https://github.com/stcmz/mccs-toolchain).

          For MCCS users, you are suggested to use the latest version of the Docker image. If you somehow need to use this specific version, please use the following command line.
          ```
          # pull from Docker Hub
          docker pull stcmz/mccs:${{ steps.get_version.outputs.version }}

          # or from GitHub Container Registry
          docker pull ghcr.io/stcmz/mccs:${{ steps.get_version.outputs.version }}
          ```
        draft: false
        prerelease: false
    -
      name: Checkout code
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: slim
        platforms: linux/amd64
        push: true
        tags: |
          stcmz/mccs:latest
          stcmz/mccs:slim
          stcmz/mccs:${{ steps.get_version.outputs.version }}
          stcmz/mccs:${{ steps.get_version.outputs.version }}-slim
          ghcr.io/stcmz/mccs:latest
          ghcr.io/stcmz/mccs:slim
          ghcr.io/stcmz/mccs:${{ steps.get_version.outputs.version }}
          ghcr.io/stcmz/mccs:${{ steps.get_version.outputs.version }}-slim